### ISSUE TITLE
Change `dirty` and `undefined` items

### ISSUE THREAD

**Issue by ZeroEkkusu** [0xPolygon/storage-layout-checker#9]
Identify non-storage items by special fields, rather than `label`.

## Context:

If you look at how 'dirty' and 'undefined' items are identified in `_reporter.js`, you'll see that the item's `label` is set to `"dirty"`/`"undefined"`.

This isn't good because it can lead to errors if there's an actual variable named `dirty` or `undefined`.

To address this issue, add an extra field to all items: `special`, which can be `true` or `false`.

In all places in the code where `.label == "undefined` or `.label == "dirty"`, instead do the following:

Check if `special` is `true`. If it is, proceed to check the label as before. If not, we're dealing with an actual variable, which means it's neither 'undefined' nor 'dirty'.

**Comment by kamuik16** [comment]
> Identify non-storage items by special fields, rather than `label`.

Hey @ZeroEkkusu! is this issue available to work? I can work on this. Maybe give me some more context for this issue? Thanks.

**Comment by ZeroEkkusu** [comment]
Sure! I've added context above.  👆

If you need more info or help, ping me, @kamuik16!

**Comment by kamuik16** [comment]
> Sure! I've added context above.  👆
> 
> If you need more info or help, ping me, @kamuik16!

Okay I understood the issue and wanted to know how can I test this on my local computer with changes I make?

**Comment by ZeroEkkusu** [comment]
@kamuik16, this is the easiest way:

When you `forge init` a new project, you'll have `src/Counter.sol` in it.
Add the tool to the project as described in the readme.

Then, `git commit`, and you'll have a commit hash.
Use it when you try running the tool.

When you try running it the first time there'll be no findings because you haven't made any changes to `Counter`.
You can change `uint256 number` to `uint128 number`, which will be enough do create a 'dirty' item in the new storage layout and an 'undefined' item in the old storage layout.

You can make changes to the tool directly in the `lib` folder of the example project, and re-run it to test it.

Once you're done you can copy over the changes from `lib/storage-delta` to your actual fork of this repository, and make a pull request.

**Comment by kamuik16** [comment]
> @kamuik16, this is the easiest way:
> 
> When you `forge init` a new project, you'll have `src/Counter.sol` in it. Add the tool to the project as described in the readme.
> 
> Then, `git commit`, and you'll have a commit hash. Use it when you try running the tool.
> 
> When you try running it the first time there'll be no findings because you haven't made any changes to `Counter`. You can change `uint256 number` to `uint128 number`, which will be enough do create a 'dirty' item in the new storage layout and an 'undefined' item in the old storage layout.
> 
> You can make changes to the tool directly in the `lib` folder of the example project, and re-run it to test it.
> 
> Once you're done you can copy over the changes from `lib/storage-delta` to your actual fork of this repository, and make a pull request.

Hey @ZeroEkkusu !

So, what I did was a bit of a workaround. Since Solidity doesn't allow the '@' symbol in variable names, I thought, why not use that to our advantage? I updated the script to label these special items as "@dirty" and "@undefined" instead. It's a simple tweak but does the trick!

Now, wherever the script used to check for .label == "undefined" or .label == "dirty", I changed it to look for our new labels. This way, we're steering clear of any potential mix-ups with real variable names in the contracts we're analyzing.

For example, if we're checking an item and it doesn't match with the new layout, instead of marking it as 'dirty', it's now '@dirty'. This small '@' makes a big difference, ensuring our script knows it's dealing with a special marker, not an actual variable named 'dirty' or 'undefined'.

I think this solution should keep things neat and avoid any confusion down the line. Let me know what you think!

I am attaching some relevant codes and their outputs.

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Counter {
    uint128 public dirty;
}
```

New Report Before:
```
🪦
    0: 16      16 dirty bytes               
```

New Report After:
```
🏴  0          dirty                        uint128
    0: 16      16 dirty bytes               
```


```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract Counter {
    uint256 public @counter;
}
```

Error by remix: 
```
ParserError: Expected identifier but got 'ILLEGAL'
 --> Counter.sol:5:20:
  |
5 |     uint256 public @counter;
  |                    ^
```

**Comment by ZeroEkkusu** [comment]
Very clever, @kamuik16! I totally didn't think of that!

Feel free to open a PR (you can use `dev`), and we'll get it merged.

**Comment by kamuik16** [comment]
> Very clever, @kamuik16! I totally didn't think of that!
> 
> Feel free to open a PR (you can use `dev`), and we'll get it merged.

https://github.com/0xPolygon/storage-delta/pull/14 Opened this PR, you can check and let me know if you want any changes.
